version: "3.4"
services:
  app:
    build: .
    depends_on:
      - postgres
    # ports:
      # - 4000:4000
    volumes:
      - ..:/opt/app
    environment:
      HISTFILE: .bash_history
      POSTGRES_HOST: postgres
    command: sleep infinity

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
